/**
 * ALCATEIA DE LEÕES — Seed das 90 Missões
 * Roda UMA VEZ para popular a tabela alcateia_missoes
 *
 * Como usar:
 * 1. Copie este arquivo para ~/alcateia-leoes/
 * 2. node seed_missoes.js
 */

require('dotenv').config();
const { createClient } = require('@supabase/supabase-js');

global.WebSocket = require('ws');
const supabase = createClient(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_SERVICE_KEY
);

const MISSOES = [
  // ═══════════════════════════════
  // SEMANA 1 — SER SACERDOTE
  // ═══════════════════════════════
  { dia: 1, semana: 1, pilar: 'Ser Sacerdote', titulo: 'O altar antes de tudo', verso: '"Mas tu, quando orares, entra no teu quarto secreto..." — Mt 6:6', palavra: 'Leão, hoje O PAPAI te chama para uma pergunta simples e brutal: você tem um altar? Não uma religião. Não um hábito. Um altar — um lugar e um tempo onde só você e Ele existem. O sacerdote de Israel não entrava na presença de Deus de passagem. Ele se preparava, se posicionava, se apresentava. Você foi chamado para o mesmo. Antes de ser pai, marido, empresário ou líder — você é sacerdote. E todo sacerdote precisa de um altar.', desafio: 'Defina hoje o seu altar: um lugar fixo e um horário fixo. Pode ser a sala às 5h, o quarto às 6h, o carro antes de entrar no trabalho. O que importa é que seja intencional. Escreva: onde e quando será a sua Tenda do Encontro daqui para frente.', reflexao: 'Você tem entrado na presença do PAPAI como obrigação religiosa ou como necessidade real? Qual é a diferença prática disso na sua vida hoje?', declaracao: 'Eu sou sacerdote. Tenho um altar. E hoje escolho entrar na presença do PAPAI antes de qualquer outra coisa.', treinamento_nome: null, treinamento_texto: null },
  { dia: 2, semana: 1, pilar: 'Ser Sacerdote', titulo: 'Sacerdote não improvisa', verso: '"Santifica-os na verdade; a tua palavra é a verdade." — Jo 17:17', palavra: 'Leão, hoje O PAPAI te chama para entender que sacerdócio exige preparo. O sacerdote levítico sabia exatamente o que fazer — não porque era talentoso, mas porque havia estudado, praticado e se submetido. O homem que improvisa no altar improvisa em casa. O homem que não tem a Palavra do PAPAI na boca não tem nada para oferecer à sua família. Santificação começa com a Palavra — e a Palavra exige que você a leia de propósito, não por acaso.', desafio: 'Leia um capítulo inteiro da Bíblia hoje — não um versículo avulso. Depois escreva com suas próprias palavras: o que O PAPAI está dizendo para a sua vida nesse texto? Uma frase. Sua frase.', reflexao: 'Quando foi a última vez que a Palavra do PAPAI mudou uma decisão concreta sua? O que estava em jogo?', declaracao: 'Eu me preparo para servir. A Palavra do PAPAI está na minha boca e nas minhas decisões.', treinamento_nome: null, treinamento_texto: null },
  { dia: 3, semana: 1, pilar: 'Ser Sacerdote', titulo: 'O sacerdote cobre, não expõe', verso: '"O amor cobre uma multidão de pecados." — 1 Pe 4:8', palavra: 'Leão, hoje O PAPAI te chama para aprender uma das funções mais esquecidas do sacerdote: cobrir. O sacerdote não expunha as falhas do povo — ele as cobria com sangue, com oração, com intercessão. Em casa, você é chamado para cobrir sua esposa e seus filhos. Cobrir significa não expor as fraquezas deles para outros. Significa orar por eles antes de corrigi-los. Significa ser o primeiro a defender, não o primeiro a criticar.', desafio: 'Hoje, ore especificamente por cada pessoa da sua família pelo nome. Não peça nada para você — interceda por eles. Se tiver filhos, coloque a mão sobre a cabeça de cada um e abençoe em voz alta.', reflexao: 'Existe alguma área da sua família que você tem exposto em vez de cobrir — com palavras, com atitudes, com silêncio? O que precisa mudar?', declaracao: 'Eu cubro minha família. Minha casa está sob o meu sacerdócio e sob a proteção do PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 4, semana: 1, pilar: 'Ser Sacerdote', titulo: 'O sacerdote abre a semana', verso: '"Quanto a mim e à minha família, serviremos ao SENHOR." — Js 24:15', palavra: 'Leão, hoje O PAPAI te chama para um ritual que muda a atmosfera da sua casa: abrir a semana como sacerdote. Josué não disse isso em um culto de domingo. Disse para toda a nação, com a família ao lado. Você tem autoridade para declarar sobre a sua casa. Toda segunda-feira é uma nova oportunidade de posicionar sua família sob a cobertura do PAPAI.', desafio: 'Na próxima segunda-feira, reúna sua família antes do dia começar — mesmo que por cinco minutos. Leia um versículo, ore em voz alta e declare uma palavra sobre a semana.', reflexao: 'Sua família sabe que você é o sacerdote da casa? Eles sentem isso na prática, ou é uma ideia que existe só na sua cabeça?', declaracao: 'Eu declaro sobre a minha casa. Minha família sabe quem lidera espiritualmente. E eu assumo esse lugar com honra diante do PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 5, semana: 1, pilar: 'Ser Sacerdote', titulo: 'O sacerdote intercede antes de agir', verso: '"Antes de tudo, exorto que se façam súplicas, orações, intercessões..." — 1 Tm 2:1', palavra: 'Leão, hoje O PAPAI te chama para inverter uma ordem que o mundo ensinou errado. O mundo diz: age, depois ore se der errado. O sacerdote diz: oro primeiro, depois ajo. Intercessão não é o plano B quando as coisas falham — é o ponto de partida de todo homem que opera como sacerdote. As maiores decisões da sua vida precisam passar pelo altar antes de passar pela planilha.', desafio: 'Identifique hoje a decisão mais urgente que você precisa tomar. Antes de agir, dedique 15 minutos de oração específica sobre essa decisão. Escreva o que você sentiu ou recebeu do PAPAI.', reflexao: 'Qual foi a última vez que você adiou uma ação para orar primeiro? O que aconteceu depois?', declaracao: 'Eu oro antes de agir. O altar vem antes da agenda. E as minhas decisões passam pela presença do PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 6, semana: 1, pilar: 'Ser Sacerdote', titulo: 'O sacerdote bendiz, não amaldiçoa', verso: '"Bendizei os que vos perseguem; bendizei, e não amaldiçoeis." — Rm 12:14', palavra: 'Leão, hoje O PAPAI te chama para examinar o que sai da sua boca. O sacerdote levítico tinha uma função específica: pronunciar bênção sobre o povo. Você foi chamado para o mesmo. O que você tem declarado sobre sua esposa, seus filhos, seus sócios, seus inimigos? Palavras de sacerdote constroem. Palavras de homem ferido destroem.', desafio: 'Hoje, escreva uma bênção específica para cada pessoa da sua família — não um elogio genérico, mas uma declaração profética do que você crê que O PAPAI tem para eles. Depois diga em voz alta para cada um.', reflexao: 'O que as pessoas mais próximas de você ouvem sair da sua boca com mais frequência — bênção ou crítica?', declaracao: 'Minha boca é instrumento de bênção do PAPAI. O que eu declaro sobre minha família tem peso e autoridade de sacerdote.', treinamento_nome: null, treinamento_texto: null },
  { dia: 7, semana: 1, pilar: 'Ser Sacerdote', titulo: 'Revisão — o sacerdote presta contas', verso: '"Cada um de nós prestará contas de si mesmo a Deus." — Rm 14:12', palavra: 'Leão, hoje O PAPAI te chama para sentar diante Dele e fazer uma pergunta honesta: como foi essa semana no sacerdócio? Não com julgamento — com honestidade. Você chegou ao final da Semana 1. Isso já é mais do que a maioria dos homens faz.', desafio: 'Escreva uma resposta honesta: (1) Qual dia desta semana você mais sentiu a presença do PAPAI? (2) Qual missão foi mais difícil? (3) O que você vai carregar desta semana para o resto dos 90 dias?', reflexao: 'Se O PAPAI te avaliasse como sacerdote esta semana — não para condenar, mas para orientar — o que Ele diria?', declaracao: 'Eu presto contas ao PAPAI. Cresci esta semana. E entro na próxima semana como um sacerdote mais firme e mais dependente do PAPAI.', treinamento_nome: 'Legendários', treinamento_texto: 'Leão, após uma semana inteira construindo o altar do sacerdote, você está pronto para uma experiência que vai aprofundar tudo o que viveu. O treinamento Legendários foi uma das experiências que transformou a minha vida. Se você ainda não passou por ele, este é o momento certo.' },

  // ═══════════════════════════════
  // SEMANA 2 — SER PROVEDOR
  // ═══════════════════════════════
  { dia: 8, semana: 2, pilar: 'Ser Provedor', titulo: 'Provedor não é sinônimo de escravo', verso: '"A bênção do SENHOR enriquece, e O PAPAI não acrescenta tristeza com ela." — Pv 10:22', palavra: 'Leão, hoje O PAPAI te chama para quebrar uma mentira que o mundo plantou: que ser provedor significa se matar de trabalhar. O homem que provê por medo não está provendo — está fugindo. Provisão bíblica nasce da bênção do PAPAI, não do suor desgastante do ego.', desafio: 'Sente e escreva honestamente: você trabalha movido por propósito ou por medo? Liste três áreas onde o medo tem sido o motor da sua provisão. Para cada uma, escreva o que seria diferente se o PAPAI fosse o motor.', reflexao: 'O que você tem sacrificado na sua família em nome da provisão financeira? Vale a troca?', declaracao: 'Eu provejo do lugar da bênção do PAPAI, não do lugar do medo. Minha provisão tem propósito, não ansiedade.', treinamento_nome: null, treinamento_texto: null },
  { dia: 9, semana: 2, pilar: 'Ser Provedor', titulo: 'As cinco dimensões da provisão', verso: '"Amado, eu desejo que você seja próspero em tudo, assim como é próspera a sua alma." — 3 Jo 1:2', palavra: 'Leão, hoje O PAPAI te chama para ampliar o que você entende por provisão. Provisão não é só dinheiro. É um leão que provê em cinco dimensões: espiritual, relacional, física, mental e financeira. Um homem que provê só financeiramente e falha nas outras quatro está quebrando sua família por dentro enquanto paga as contas por fora.', desafio: 'Avalie sua provisão nas cinco dimensões. Dê uma nota de 1 a 5 para cada uma. Identifique a mais fraca e escreva uma ação concreta para esta semana.', reflexao: 'Sua família sente abundância na sua presença ou sente que você está sempre ausente mesmo quando está em casa?', declaracao: 'Eu provejo nas cinco dimensões. Minha família não tem falta de mim — em nenhuma área.', treinamento_nome: null, treinamento_texto: null },
  { dia: 10, semana: 2, pilar: 'Ser Provedor', titulo: 'O provedor tem ordem na casa', verso: '"O que é fiel no pouco também é fiel no muito." — Lc 16:10', palavra: 'Leão, hoje O PAPAI te chama para olhar para dentro da sua própria casa antes de falar em provisão para o mundo. O homem que não sabe para onde vai o dinheiro da sua casa não tem autoridade para falar em legado. Fidelidade no pouco é o passaporte para o muito.', desafio: 'Abra suas finanças pessoais: você sabe quanto entra e quanto sai todo mês? Se não souber, monte agora um orçamento simples — receita, despesas fixas, variáveis, sobra.', reflexao: 'Existe alguma área financeira que você tem evitado encarar? O que o medo de olhar está custando para você?', declaracao: 'Eu tenho ordem na minha casa. O PAPAI me confia mais porque sou fiel no que já tenho.', treinamento_nome: null, treinamento_texto: null },
  { dia: 11, semana: 2, pilar: 'Ser Provedor', titulo: 'O provedor não rouba do futuro', verso: '"O homem de bem deixa herança aos filhos dos seus filhos." — Pv 13:22', palavra: 'Leão, hoje O PAPAI te chama para pensar além do mês que vem. Roubar do futuro é gastar hoje o que seus filhos precisariam amanhã. O provedor bíblico pensa em gerações.', desafio: 'Escreva o que você quer deixar para seus filhos em três dimensões: financeira, espiritual e relacional. Isso é o seu testamento de provedor. Guarde e releia no Dia 90.', reflexao: 'Se você morresse hoje, o que seus filhos herdariam além de bens materiais? Essa herança é intencional ou acidental?', declaracao: 'Eu construo para gerações. Minha provisão hoje é a herança do PAPAI para os meus filhos amanhã.', treinamento_nome: null, treinamento_texto: null },
  { dia: 12, semana: 2, pilar: 'Ser Provedor', titulo: 'O provedor trabalha com vocação', verso: '"O que a tua mão encontrar para fazer, faze-o com todo o teu poder." — Ec 9:10', palavra: 'Leão, hoje O PAPAI te chama para conectar seu trabalho com seu chamado. Há uma diferença brutal entre um homem que trabalha para sobreviver e um homem que trabalha porque foi chamado. Quando o trabalho está alinhado com o propósito, a provisão vem com paz.', desafio: 'Responda: o que você faz no trabalho que faz o tempo passar sem perceber? O que as pessoas dizem que você faz melhor que ninguém? Essas duas respostas apontam para onde O PAPAI quer que sua provisão venha.', reflexao: 'Você está trabalhando no lugar certo? Ou está provendo financeiramente mas morrendo por dentro?', declaracao: 'Meu trabalho é vocação, não prisão. Eu provejo com propósito e O PAPAI honra o que faço com excelência.', treinamento_nome: null, treinamento_texto: null },
  { dia: 13, semana: 2, pilar: 'Ser Provedor', titulo: 'O provedor não carrega sozinho', verso: '"Melhor é serem dois do que um." — Ec 4:9', palavra: 'Leão, hoje O PAPAI te chama para largar um peso que você carregou sem precisar: a ideia de que provisão é responsabilidade exclusivamente sua. O homem que não deixa ninguém ajudá-lo não é forte — é orgulhoso.', desafio: 'Hoje, tenha uma conversa honesta com sua esposa sobre a divisão das responsabilidades. O que você está carregando sozinho que deveria ser compartilhado?', reflexao: 'O orgulho de resolver tudo sozinho já te custou algo importante? O que foi?', declaracao: 'Eu não carrego sozinho. O PAPAI é meu sócio, minha esposa é minha parceira e juntos provemos mais.', treinamento_nome: null, treinamento_texto: null },
  { dia: 14, semana: 2, pilar: 'Ser Provedor', titulo: 'Revisão — o provedor presta contas', verso: '"Dê, pois, cada um conforme determinou em seu coração." — 2 Co 9:7', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana do provedor. Você olhou para as cinco dimensões, encarou as finanças, pensou em herança e conectou trabalho com vocação.', desafio: 'Escreva: (1) Em qual dimensão você mais cresceu? (2) Qual verdade mais incomodou? (3) Que ação concreta vai implementar permanentemente?', reflexao: 'Se O PAPAI olhasse para a sua provisão hoje — nas cinco dimensões — o que Ele diria?', declaracao: 'Eu sou provedor. Não por obrigação, mas por chamado. E o PAPAI me capacita para prover bem em tudo que importa.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 3 — SER PROTETOR
  // ═══════════════════════════════
  { dia: 15, semana: 3, pilar: 'Ser Protetor', titulo: 'Protetor, não controlador', verso: '"O SENHOR é o teu guarda; o SENHOR é a tua sombra à tua mão direita." — Sl 121:5', palavra: 'Leão, hoje O PAPAI te chama para entender a diferença entre proteger e controlar. O homem que controla tem medo. O homem que protege tem autoridade. Controle aprisiona quem você ama. Proteção libera quem você ama para florescer dentro de um perímetro seguro.', desafio: 'Liste três áreas onde você tem exercido controle disfarçado de proteção. Para cada uma, escreva o que seria diferente se você substituísse o controle por confiança e oração.', reflexao: 'As pessoas que você ama se sentem protegidas por você ou se sentem vigiadas?', declaracao: 'Eu protejo sem aprisionar. Minha família floresce sob minha cobertura porque O PAPAI me ensinou a guardar, não a controlar.', treinamento_nome: null, treinamento_texto: null },
  { dia: 16, semana: 3, pilar: 'Ser Protetor', titulo: 'O protetor vigia a porta', verso: '"Sede sóbrios e vigilantes. O diabo anda em derredor, como leão que ruge, procurando alguém para devorar." — 1 Pe 5:8', palavra: 'Leão, hoje O PAPAI te chama para vigiar o que entra na sua casa — não só pela porta física, mas pelas telas, pelas conversas, pelas amizades, pelo conteúdo que seus filhos consomem. Hoje a porta da sua cidade é o Wi-Fi, é o celular, são as amizades dos seus filhos.', desafio: 'Faça uma auditoria do que entra na sua casa. Identifique uma porta aberta que precisa ser fechada e tome uma ação concreta.', reflexao: 'O que está entrando na sua casa que você tem tolerado porque dá trabalho confrontar?', declaracao: 'Eu vigio a porta da minha casa. O que entra sob o meu teto passa pelo filtro do PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 17, semana: 3, pilar: 'Ser Protetor', titulo: 'O protetor protege a alma', verso: '"Acima de tudo, guarda o teu coração, porque dele procedem as fontes da vida." — Pv 4:23', palavra: 'Leão, hoje O PAPAI te chama para a proteção mais negligenciada: a proteção da alma. O homem que não cuida do próprio coração não tem nada para oferecer à família. Um leão com alma ferida protege com raiva, não com amor.', desafio: 'Identifique uma ferida antiga que ainda está ativa na sua alma. Leve isso ao altar do PAPAI com honestidade. Se precisar de ajuda profissional, dê o primeiro passo hoje.', reflexao: 'O que você tem consumido que está corroendo sua alma por dentro? Você tem sido protetor de si mesmo?', declaracao: 'Eu guardo meu coração. Um leão com alma sã protege com amor. Um leão com alma ferida fere quem ama.', treinamento_nome: null, treinamento_texto: null },
  { dia: 18, semana: 3, pilar: 'Ser Protetor', titulo: 'O protetor fala verdade com amor', verso: '"Mas, seguindo a verdade em amor, cresçamos em tudo nele." — Ef 4:15', palavra: 'Leão, hoje O PAPAI te chama para um dos atos de proteção mais corajosos: dizer a verdade. O homem que fica em silêncio para evitar conflito não está protegendo — está abandonando. Verdade sem amor destrói, e silêncio por covardia abandona.', desafio: 'Identifique uma conversa que você tem evitado por medo do conflito. Prepare o que vai dizer com verdade e amor. Marque a conversa para esta semana.', reflexao: 'Você tem sido covarde com a verdade em nome da paz? O que esse silêncio tem custado para quem você ama?', declaracao: 'Eu falo a verdade com amor. Minha família pode contar comigo para ouvir o que precisa ouvir.', treinamento_nome: null, treinamento_texto: null },
  { dia: 19, semana: 3, pilar: 'Ser Protetor', titulo: 'O protetor protege o nome da família', verso: '"O bom nome é mais desejável do que as grandes riquezas." — Pv 22:1', palavra: 'Leão, hoje O PAPAI te chama para proteger algo que dinheiro não compra de volta: o nome da sua família. Seu nome é um ativo espiritual. Proteja-o como tal.', desafio: 'Escreva o que você quer que as pessoas digam sobre o nome da sua família daqui a 20 anos. Suas ações desta semana estão construindo ou destruindo esse legado?', reflexao: 'Existe alguma área da sua vida onde o nome da sua família está em risco?', declaracao: 'Eu protejo o nome da minha família. O que construo com integridade é o sobrenome que meus filhos vão carregar com orgulho.', treinamento_nome: null, treinamento_texto: null },
  { dia: 20, semana: 3, pilar: 'Ser Protetor', titulo: 'O protetor tem limites saudáveis', verso: '"Não entreis pela porta larga, porque larga é a porta que conduz à perdição." — Mt 7:13', palavra: 'Leão, hoje O PAPAI te chama para entender que proteção exige limites. O homem que não consegue dizer não não está protegendo nada. Limite não é egoísmo — é gestão da sua energia para que o que importa receba o melhor de você.', desafio: 'Identifique três compromissos ou hábitos que consomem energia da sua família sem retornar nada. Para cada um, escreva um limite claro que vai estabelecer esta semana.', reflexao: 'Você tem dificuldade de dizer não? De onde vem esse medo?', declaracao: 'Eu tenho limites. O que entra no meu tempo e na minha energia passa pelo filtro do PAPAI e pelo bem da minha família.', treinamento_nome: null, treinamento_texto: null },
  { dia: 21, semana: 3, pilar: 'Ser Protetor', titulo: 'Revisão — o protetor presta contas', verso: '"Sede fortes e corajosos. Não temais, porque o SENHOR teu Deus é quem vai contigo." — Dt 31:6', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana do protetor. Três semanas completas. Você está construindo algo real.', desafio: 'Escreva: (1) Qual porta você fechou esta semana? (2) Qual conversa corajosa você teve? (3) O que aprendeu sobre si mesmo como protetor?', reflexao: 'Sua família se sente mais segura com você esta semana do que há três semanas?', declaracao: 'Eu sou protetor. Não por força própria, mas pela autoridade que O PAPAI me deu. Minha casa é um lugar seguro.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 4 — SER PRESENTE
  // ═══════════════════════════════
  { dia: 22, semana: 4, pilar: 'Ser Presente', titulo: 'Presente de corpo e alma', verso: '"Eis que estou à porta e bato." — Ap 3:20', palavra: 'Leão, hoje O PAPAI te chama para uma pergunta que dói: quando foi a última vez que você estava realmente presente? Estar no mesmo cômodo não é presença. Presença é quando sua família sente que você está inteiramente ali.', desafio: 'Hoje, escolha um momento com sua família e esteja 100% presente. Celular em outro cômodo. Sem exceção. Depois escreva o que percebeu.', reflexao: 'Seus filhos ou sua esposa já pediram sua atenção enquanto você estava presente mas ausente? O que eles sentiram?', declaracao: 'Eu estou presente. Quando estou com minha família, estou inteiro. Minha presença é um presente do PAPAI para eles.', treinamento_nome: null, treinamento_texto: null },
  { dia: 23, semana: 4, pilar: 'Ser Presente', titulo: 'O celular não é mais importante que seu filho', verso: '"Deixai os pequeninos virem a mim e não os impeçais." — Mc 10:14', palavra: 'Leão, hoje O PAPAI te chama para encarar o ladrão de presença mais poderoso da sua geração: o celular. Quando seu filho vem até você e você está no celular, ele aprende: papai tem coisas mais importantes do que eu.', desafio: 'Estabeleça uma regra clara na sua casa: qual é o horário sem celular? Se tem filhos pequenos, implemente 20 minutos no chão com eles, sem interrupção digital.', reflexao: 'Se seus filhos descrevessem seu relacionamento com o celular, o que eles diriam?', declaracao: 'Meus filhos são mais importantes que qualquer notificação. Quando eles vêm até mim, O PAPAI está me dando uma oportunidade de formá-los.', treinamento_nome: null, treinamento_texto: null },
  { dia: 24, semana: 4, pilar: 'Ser Presente', titulo: 'Presença é memória', verso: '"Estas palavras estarão no teu coração... quando estiveres em casa e quando caminhares." — Dt 6:6-7', palavra: 'Leão, hoje O PAPAI te chama para pensar em memórias. Seus filhos não vão lembrar do carro que você dirigia. Vão lembrar da sua presença — ou da sua ausência. A presença intencional cria memórias que formam identidade e fé.', desafio: 'Hoje, crie uma memória intencional com um filho ou com sua esposa. O critério é: você estará presente de verdade e eles vão lembrar.', reflexao: 'Qual é a memória mais forte que você tem do seu pai? O que você quer que seus filhos lembrem de você?', declaracao: 'Eu crio memórias. Minha presença hoje é a herança emocional do PAPAI que meus filhos vão carregar para sempre.', treinamento_nome: null, treinamento_texto: null },
  { dia: 25, semana: 4, pilar: 'Ser Presente', titulo: 'O homem presente ouve antes de falar', verso: '"Sede prontos para ouvir, tardios para falar." — Tg 1:19', palavra: 'Leão, hoje O PAPAI te chama para desenvolver a habilidade mais rara nos homens: ouvir de verdade. Sua esposa não quer sempre uma solução. Às vezes ela quer ser ouvida. Presença começa pelos ouvidos antes da boca.', desafio: 'Hoje, tenha uma conversa onde sua única regra é: não fale até a outra pessoa terminar completamente. Faça perguntas para entender — não para resolver.', reflexao: 'As pessoas da sua casa se sentem ouvidas por você? Ou sentem que você já tem a resposta antes de ouvir?', declaracao: 'Eu ouço antes de falar. Minha presença começa pelos ouvidos. Quem fala comigo sabe que está sendo ouvido de verdade.', treinamento_nome: null, treinamento_texto: null },
  { dia: 26, semana: 4, pilar: 'Ser Presente', titulo: 'Presente no sofrimento', verso: '"Chorai com os que choram." — Rm 12:15', palavra: 'Leão, hoje O PAPAI te chama para a forma mais difícil de presença: estar presente no sofrimento sem tentar consertá-lo. Às vezes a maior coisa que você pode fazer é sentar ao lado e não dizer nada. Jesus chorou diante do túmulo de Lázaro mesmo sabendo que ia ressuscitá-lo.', desafio: 'Hoje, pense em alguém da sua família que está passando por algo difícil. Não dê conselho — dê presença. Uma ligação, uma visita, um abraço sem palavras.', reflexao: 'Você foge do sofrimento alheio porque não sabe o que dizer? O que te impede de estar presente sem resolver?', declaracao: 'Eu estou presente no sofrimento. Não fujo da dor de quem amo. O PAPAI me deu coragem para sentar no lugar difícil.', treinamento_nome: null, treinamento_texto: null },
  { dia: 27, semana: 4, pilar: 'Ser Presente', titulo: 'Presente no cotidiano', verso: '"Portanto, não vos preocupeis com o dia de amanhã." — Mt 6:34', palavra: 'Leão, hoje O PAPAI te chama para encontrá-Lo no cotidiano. A maioria dos homens vive no futuro e perde o presente que está acontecendo agora. Seu filho tem sete anos hoje. Amanhã ele tem oito. Você não recupera o jantar de ontem.', desafio: 'Hoje, faça algo completamente ordinário com sua família com atenção total: o café, o caminho para a escola, o jantar. Sem pressa, sem celular.', reflexao: 'Você tem esperado os momentos grandes para estar presente? Quantos momentos pequenos e preciosos você já perdeu?', declaracao: 'Eu estou presente no cotidiano. Os momentos ordinários com minha família são extraordinários para O PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 28, semana: 4, pilar: 'Ser Presente', titulo: 'Revisão — o presente presta contas', verso: '"Remite o teu caminho ao SENHOR; confia nele, e ele tudo fará." — Sl 37:5', palavra: 'Leão, hoje O PAPAI te chama para revisar quatro semanas de jornada. Sacerdote, Provedor, Protetor, Presente. A Fase 1 está completa. Você não é mais o homem que começou no Dia 1.', desafio: 'Escreva uma carta para si mesmo: (1) Maior transformação das quatro semanas. (2) Qual pilar precisa de mais atenção. (3) O que sua família percebeu de diferente em você. Guarde para o Dia 90.', reflexao: 'O que mudou de concreto nas suas relações desde o Dia 1?', declaracao: 'Eu cheguei até aqui. Não por força própria — pela graça do PAPAI. E vou até o Dia 90 porque o milagre começa quando as desculpas terminam.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 5 — SER PRÓSPERO
  // ═══════════════════════════════
  { dia: 29, semana: 5, pilar: 'Ser Próspero', titulo: 'Prosperidade começa na alma', verso: '"Amado, eu desejo que você seja próspero em tudo, assim como é próspera a sua alma." — 3 Jo 1:2', palavra: 'Leão, hoje O PAPAI te chama para entender que prosperidade exterior sem prosperidade interior é uma armadilha. Se sua alma está pobre — amarga, ansiosa, sem paz — não existe dinheiro que compense.', desafio: 'Avalie a saúde da sua alma em três áreas: paz interior, gratidão e ausência de amargura. Dê uma nota de 1 a 5 para cada uma. Leve ao altar do PAPAI.', reflexao: 'Você tem buscado prosperidade financeira enquanto negligencia a prosperidade da sua alma?', declaracao: 'Minha prosperidade começa por dentro. O PAPAI prospera minha alma antes de prosperar minha conta.', treinamento_nome: null, treinamento_texto: null },
  { dia: 30, semana: 5, pilar: 'Ser Próspero', titulo: 'O leão próspero dá antes de receber', verso: '"Dai, e ser-vos-á dado; boa medida, recalcada, sacudida e transbordante." — Lc 6:38', palavra: 'Leão, hoje O PAPAI te chama para o princípio que vai contra toda lógica financeira: dar primeiro. Generosidade não é o que você faz quando sobra. É o que você faz primeiro.', desafio: 'Hoje, dê algo de valor — dinheiro, tempo, habilidade — para alguém que não pode te pagar de volta. Não espere sobrar. Dê agora.', reflexao: 'Você tem dado por obrigação religiosa ou por alegria genuína?', declaracao: 'Eu dou primeiro. A generosidade do PAPAI flui através de mim e o que eu solto volta multiplicado.', treinamento_nome: null, treinamento_texto: null },
  { dia: 31, semana: 5, pilar: 'Ser Próspero', titulo: 'O leão próspero administra bem', verso: '"Sede diligentes nos negócios." — Rm 12:11', palavra: 'Leão, hoje O PAPAI te chama para a face prática da prosperidade: diligência. Sonho sem execução é devaneio. Administração diligente é respeito pelo que O PAPAI colocou nas suas mãos.', desafio: 'Identifique uma área onde você tem sido negligente — um projeto parado, uma dívida evitada. Dê um passo concreto hoje.', reflexao: 'Onde você tem esperado milagre onde O PAPAI está esperando diligência?', declaracao: 'Eu sou diligente. O PAPAI me confia abundância porque cuido com excelência do que já tenho.', treinamento_nome: null, treinamento_texto: null },
  { dia: 32, semana: 5, pilar: 'Ser Próspero', titulo: 'Prosperidade e gratidão', verso: '"Em tudo dai graças, porque esta é a vontade de Deus." — 1 Ts 5:18', palavra: 'Leão, hoje O PAPAI te chama para o combustível mais poderoso da prosperidade: gratidão. O homem que não é grato pelo que tem hoje não está pronto para administrar mais.', desafio: 'Escreva 10 coisas pelas quais você é genuinamente grato — específico, não genérico. Leia em voz alta como declaração ao PAPAI.', reflexao: 'Você reclama mais do que agradece? O que sua família ouve mais?', declaracao: 'Eu sou grato. A prosperidade do PAPAI já está na minha vida e minha gratidão abre espaço para mais.', treinamento_nome: null, treinamento_texto: null },
  { dia: 33, semana: 5, pilar: 'Ser Próspero', titulo: 'O leão próspero investe em pessoas', verso: '"O que empresta ao pobre empresta ao SENHOR." — Pv 19:17', palavra: 'Leão, hoje O PAPAI te chama para o investimento com maior retorno eterno: pessoas. O leão que investe só em ativos financeiros morre rico e deixa herdeiros pobres de alma.', desafio: 'Identifique uma pessoa em quem pode investir intencionalmente. Faça um investimento concreto: tempo, conhecimento ou recurso.', reflexao: 'Para onde vai o excedente da sua prosperidade — para acumular ou para investir em pessoas?', declaracao: 'Eu invisto em pessoas. O retorno eterno do PAPAI vem através das vidas que toco com o que Ele me deu.', treinamento_nome: null, treinamento_texto: null },
  { dia: 34, semana: 5, pilar: 'Ser Próspero', titulo: 'Prosperidade sem idolatria', verso: '"Não podeis servir a Deus e às riquezas." — Mt 6:24', palavra: 'Leão, hoje O PAPAI te chama para uma linha que não pode ser cruzada: prosperidade que vira idolatria. Quando o dinheiro define sua identidade, quando a perda financeira destrói sua paz — o dinheiro virou seu deus.', desafio: 'Faça o teste da idolatria financeira: se você perdesse metade do que tem amanhã, o que aconteceria com sua paz e sua fé? Escreva a resposta honesta.', reflexao: 'O quanto sua identidade está atrelada ao seu sucesso financeiro?', declaracao: 'Eu tenho dinheiro, mas o dinheiro não me tem. Minha identidade está no PAPAI, não no meu extrato.', treinamento_nome: null, treinamento_texto: null },
  { dia: 35, semana: 5, pilar: 'Ser Próspero', titulo: 'Revisão — o próspero presta contas', verso: '"O SENHOR te abençoará em tudo quanto fizeres." — Dt 15:18', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana da prosperidade. Cinco semanas completas. Você está na metade da jornada.', desafio: 'Escreva: (1) Qual verdade mais te desafiou? (2) Que ação financeira vai implementar? (3) Como sua relação com dinheiro mudou desde o Dia 1?', reflexao: 'Você é mais próspero hoje — não em dinheiro, mas em perspectiva e gratidão?', declaracao: 'Eu sou próspero porque O PAPAI me ensinou a administrar, a dar e a ser grato.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 6 — HONRAR A ESPOSA
  // ═══════════════════════════════
  { dia: 36, semana: 6, pilar: 'Honrar a Esposa', titulo: 'Honrar é uma escolha, não um sentimento', verso: '"Maridos, amai vossas mulheres, como Cristo amou a igreja." — Ef 5:25', palavra: 'Leão, hoje O PAPAI te chama para entender que honrar sua esposa não depende de como você está se sentindo. Amor que só funciona quando está fácil não é amor — é conveniência.', desafio: 'Hoje, faça um gesto concreto de honra para sua esposa sem expectativa de retorno — e sem contar que é parte de um treinamento. Que seja genuíno.', reflexao: 'Você tem amado sua esposa de forma condicional? Como seria diferente se fosse uma escolha diária?', declaracao: 'Eu honro minha esposa por escolha, não por sentimento. O amor do PAPAI em mim ama ela nos dias fáceis e nos difíceis.', treinamento_nome: null, treinamento_texto: null },
  { dia: 37, semana: 6, pilar: 'Honrar a Esposa', titulo: 'O que sua esposa realmente precisa', verso: '"O marido deve cumprir o seu dever para com a mulher." — 1 Co 7:3', palavra: 'Leão, hoje O PAPAI te chama para uma pergunta que poucos homens fazem: você sabe o que sua esposa realmente precisa de você? Muitos homens provem o que a esposa não pediu e não entregam o que ela mais quer: presença, atenção, ser vista.', desafio: 'Hoje, pergunte diretamente para sua esposa: "O que você mais precisa de mim nesta fase?" Ouça sem defender. Escreva o que ela disse.', reflexao: 'Você tem assumido que sabe o que sua esposa precisa sem perguntar?', declaracao: 'Eu pergunto antes de assumir. Minha esposa sabe que o que ela precisa importa para mim e para O PAPAI.', treinamento_nome: null, treinamento_texto: null },
  { dia: 38, semana: 6, pilar: 'Honrar a Esposa', titulo: 'Cuidar é proteger a visão dela', verso: '"Igualmente vós, maridos, sede prudentes no viver com elas... como coerdeiras da graça da vida." — 1 Pe 3:7', palavra: 'Leão, hoje O PAPAI te chama para entender que sua esposa é coerdeira do Reino. Ela tem visão, chamado e propósito próprios. Cuidar dela inclui perguntar sobre os sonhos dela e criar espaço para ela florescer.', desafio: 'Hoje, pergunte para sua esposa qual é o sonho que ainda não realizou. Depois pense em uma coisa que pode fazer para ajudá-la a dar um passo nessa direção.', reflexao: 'Você conhece o sonho mais profundo da sua esposa?', declaracao: 'Minha esposa é coerdeira do PAPAI. Eu cuido do sonho dela como cuido do meu.', treinamento_nome: null, treinamento_texto: null },
  { dia: 39, semana: 6, pilar: 'Honrar a Esposa', titulo: 'Honrar em público e em privado', verso: '"A mulher virtuosa é a coroa do seu marido." — Pv 12:4', palavra: 'Leão, hoje O PAPAI te chama para examinar o que você faz com o nome da sua esposa. O que você fala sobre ela quando não está perto? O leão que honra a esposa em público consolida o que constrói em privado.', desafio: 'Hoje, diga algo específico de honra sobre sua esposa para alguém. Não genérico: algo concreto que admira nela. Depois conte para ela.', reflexao: 'O que as pessoas pensam da sua esposa com base no que você fala sobre ela?', declaracao: 'Eu honro minha esposa em público e em privado. O que falo sobre ela constrói o legado que deixamos juntos.', treinamento_nome: null, treinamento_texto: null },
  { dia: 40, semana: 6, pilar: 'Honrar a Esposa', titulo: 'O homem que pede perdão', verso: '"Confessai as vossas ofensas uns aos outros." — Tg 5:16', palavra: 'Leão, hoje O PAPAI te chama para o ato de honra mais difícil: pedir perdão. Não o perdão defensivo. O perdão específico, que nomeia o erro, que reconhece o impacto. Humildade não é fraqueza — é a força do homem que não precisa estar certo para estar bem.', desafio: 'Hoje, pense em algo específico pelo qual deve pedir perdão à sua esposa. Vá até ela, olhe nos olhos, e peça perdão sem justificativas.', reflexao: 'Você tem dificuldade de pedir perdão? De onde vem isso?', declaracao: 'Eu peço perdão quando erro. Minha humildade diante da minha esposa é honra ao PAPAI que me deu ela.', treinamento_nome: null, treinamento_texto: null },
  { dia: 41, semana: 6, pilar: 'Honrar a Esposa', titulo: 'Intimidade além do físico', verso: '"Estavam ambos nus e não se envergonhavam." — Gn 2:25', palavra: 'Leão, hoje O PAPAI te chama para o tipo de intimidade mais raro nos casamentos: a emocional e espiritual. O leão que abre o coração para a esposa — com os medos reais, os sonhos verdadeiros — constrói um pacto que o tempo não desfaz.', desafio: 'Hoje, compartilhe com sua esposa algo que normalmente não compartilha — um medo, uma insegurança, um sonho. Apenas seja vulnerável.', reflexao: 'Sua esposa conhece quem você realmente é por dentro? Ou ela conhece a versão que você permite?', declaracao: 'Eu me abro para minha esposa. A intimidade real do PAPAI começa quando eu tiro a máscara.', treinamento_nome: null, treinamento_texto: null },
  { dia: 42, semana: 6, pilar: 'Honrar a Esposa', titulo: 'Revisão — o honrador presta contas', verso: '"Sede bondosos e compassivos uns para com os outros." — Ef 4:32', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana de honrar a esposa. Seis semanas completas. Você está no ponto de virada da jornada.', desafio: 'Escreva: (1) Qual foi o gesto de honra que mais impactou sua esposa? (2) O que você aprendeu sobre ela? (3) Como o casamento está diferente hoje do Dia 1?', reflexao: 'Se sua esposa descrevesse como você a tem tratado, o que ela diria?', declaracao: 'Eu honro minha esposa. Não porque ela é perfeita, mas porque O PAPAI me chamou para amá-la como Cristo amou a Igreja.', treinamento_nome: 'Veredas Antigas — UDF', treinamento_texto: 'Leão, após seis semanas construindo os pilares fundamentais — você está pronto para aprofundar o que O PAPAI iniciou em você. As Veredas Antigas da UDF foi um dos treinamentos que mais formou minha intimidade com O PAPAI e meu posicionamento como homem. Se você sente que há mais profundidade espiritual a ser alcançada, este é o próximo passo.' },

  // ═══════════════════════════════
  // SEMANA 7 — VIVER O PROPÓSITO 1
  // ═══════════════════════════════
  { dia: 43, semana: 7, pilar: 'Viver o Propósito', titulo: 'Você foi criado com propósito', verso: '"Antes de te formar no ventre materno, Eu te conheci." — Jr 1:5', palavra: 'Leão, hoje O PAPAI te chama para uma verdade que muda tudo: você não foi um acidente. Antes de você existir, O PAPAI já tinha um plano. O problema não é falta de propósito — é que você ainda não parou para perguntar qual é o seu.', desafio: 'Escreva sem filtro: (1) O que faria se soubesse que não podia falhar? (2) O que te faz sentir mais vivo? (3) Pelo que quer ser lembrado daqui a 50 anos?', reflexao: 'Você tem vivido para o propósito do PAPAI ou para as expectativas de outras pessoas?', declaracao: 'Eu fui criado com propósito. O PAPAI me conheceu antes de eu existir e tenho um chamado que só eu posso cumprir.', treinamento_nome: null, treinamento_texto: null },
  { dia: 44, semana: 7, pilar: 'Viver o Propósito', titulo: 'Propósito tem endereço', verso: '"Levanta-te, pois, e vai." — At 22:10', palavra: 'Leão, hoje O PAPAI te chama para tirar o propósito da teoria. Propósito sem endereço é sonho. Propósito com endereço é missão. Paulo ouviu vai — e foi.', desafio: 'Transforme seu propósito em uma frase de ação: "Eu fui chamado para [verbo] [quem/o quê] através de [como]." Escreva a sua.', reflexao: 'O que está impedindo você de agir no seu propósito — medo, falta de recursos, opinião alheia?', declaracao: 'Meu propósito tem endereço. Eu sei para onde fui chamado e O PAPAI abre o caminho quando dou o primeiro passo.', treinamento_nome: null, treinamento_texto: null },
  { dia: 45, semana: 7, pilar: 'Viver o Propósito', titulo: 'O propósito passa pelo sofrimento', verso: '"E não somente isso, mas também nos gloriamos nas tribulações." — Rm 5:3', palavra: 'Leão, hoje O PAPAI te chama para uma verdade incômoda: o propósito costuma passar pelo sofrimento. José foi para o poço antes do palácio. O sofrimento que você viveu não foi desperdício — foi formação.', desafio: 'Escreva sobre a dor mais significativa da sua vida. Depois escreva: o que essa dor desenvolveu em você? Como se conecta com o seu propósito?', reflexao: 'Você tem ressentimento de algum sofrimento? Consegue enxergar como O PAPAI usou isso para te formar?', declaracao: 'Meu sofrimento não foi desperdício. O PAPAI usou cada dor para me formar para o propósito que só eu posso cumprir.', treinamento_nome: null, treinamento_texto: null },
  { dia: 46, semana: 7, pilar: 'Viver o Propósito', titulo: 'Propósito e vocação profissional', verso: '"E tudo quanto fizerdes, fazei-o de todo o coração, como ao Senhor." — Cl 3:23', palavra: 'Leão, hoje O PAPAI te chama para conectar propósito com trabalho. Você não tem uma vida espiritual e uma vida profissional — tem uma vida, e ela toda é do Reino.', desafio: 'Responda: como o seu trabalho atual se conecta com o seu propósito? Se não se conecta, escreva o que precisaria mudar e dê um passo nessa direção.', reflexao: 'Você vai para o trabalho por obrigação ou por chamado?', declaracao: 'Meu trabalho é expressão do meu propósito. Eu sirvo ao PAPAI em tudo que faço, não apenas no domingo.', treinamento_nome: null, treinamento_texto: null },
  { dia: 47, semana: 7, pilar: 'Viver o Propósito', titulo: 'O propósito exige comunidade', verso: '"O ferro afia o ferro, assim o homem afia o seu próximo." — Pv 27:17', palavra: 'Leão, hoje O PAPAI te chama para largar o mito do leão solitário. Nenhum homem cumpre seu propósito sozinho. O leão que não tem alcateia é o mais vulnerável da savana.', desafio: 'Identifique dois ou três homens com quem pode construir uma alcateia real — relação de cobertura mútua e responsabilidade.', reflexao: 'Você tem amizades masculinas profundas onde pode ser honesto sobre suas falhas e seus sonhos?', declaracao: 'Eu não caminho sozinho. O PAPAI me deu uma alcateia e juntos cumprimos o que nenhum cumpriria sozinho.', treinamento_nome: null, treinamento_texto: null },
  { dia: 48, semana: 7, pilar: 'Viver o Propósito', titulo: 'O propósito dá sentido ao sacrifício', verso: '"Corramos com perseverança a carreira que nos está proposta." — Hb 12:1', palavra: 'Leão, hoje O PAPAI te chama para entender por que você aguenta. O homem sem propósito claro abandona no primeiro obstáculo. O homem com propósito claro aguenta porque o sofrimento tem sentido.', desafio: 'Escreva o seu porquê — não o que quer alcançar, mas por quem e para quê está disposto a sacrificar. Cole em algum lugar visível.', reflexao: 'Quando você quer desistir, o que te mantém? Se a resposta for vaga, seu propósito ainda não está claro.', declaracao: 'Eu sei por que corro. O PAPAI me deu um propósito que vale cada sacrifício e cada obstáculo.', treinamento_nome: null, treinamento_texto: null },
  { dia: 49, semana: 7, pilar: 'Viver o Propósito', titulo: 'Revisão — o propósito toma forma', verso: '"Porque eu sei os planos que tenho para vós, diz o SENHOR." — Jr 29:11', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana em que o propósito começou a tomar forma. Sete semanas. Você está nos dois terços da jornada.', desafio: 'Escreva: (1) Sua frase de propósito revisada. (2) Qual passo concreto vai dar esta semana. (3) Quem vai convidar para a sua alcateia.', reflexao: 'Você está mais claro sobre seu propósito hoje do que no Dia 1? O que O PAPAI tem mostrado?', declaracao: 'Meu propósito está tomando forma. O PAPAI sabe os planos que tem para mim e eu confio nele para cada passo.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 8 — VIVER O PROPÓSITO 2
  // ═══════════════════════════════
  { dia: 50, semana: 8, pilar: 'Viver o Propósito', titulo: 'Do diagnóstico para a execução', verso: '"A fé, se não tiver obras, é morta em si mesma." — Tg 2:17', palavra: 'Leão, hoje O PAPAI te chama para o momento da virada: parar de diagnosticar e começar a executar. O propósito que fica só na cabeça não é propósito — é fantasia bem articulada.', desafio: 'Identifique a ação mais importante em direção ao seu propósito que ainda não tomou. Não a mais fácil — a mais importante. Tome essa ação hoje.', reflexao: 'O que você tem esperado para começar? Quando esse depois vai chegar?', declaracao: 'Eu ajo. Minha fé tem pernas e O PAPAI honra o passo que dou mesmo sem ver o caminho inteiro.', treinamento_nome: null, treinamento_texto: null },
  { dia: 51, semana: 8, pilar: 'Viver o Propósito', titulo: 'O propósito nos relacionamentos', verso: '"Ninguém vive para si mesmo." — Rm 14:7', palavra: 'Leão, hoje O PAPAI te chama para perceber que propósito não é individual — é relacional. Seu propósito sempre envolve outras pessoas. O leão que busca propósito como realização pessoal se encontra sozinho no topo.', desafio: 'Identifique três pessoas cujas vidas seriam impactadas se você vivesse plenamente o seu propósito. Escreva como cada uma seria diferente.', reflexao: 'Seu propósito é centrado em você ou em outras pessoas?', declaracao: 'Meu propósito serve. Eu fui chamado para impactar vidas e O PAPAI coloca as pessoas certas no meu caminho.', treinamento_nome: null, treinamento_texto: null },
  { dia: 52, semana: 8, pilar: 'Viver o Propósito', titulo: 'Propósito e disciplina diária', verso: '"Exercita-te na piedade." — 1 Tm 4:7', palavra: 'Leão, hoje O PAPAI te chama para o lado menos glamoroso do propósito: a disciplina diária. É a repetição diária que constrói o homem de propósito. Disciplina não é punição — é o custo do propósito.', desafio: 'Defina três rituais diários que vai manter pelos próximos 30 dias: um espiritual, um relacional e um profissional. Escreva os três com horário.', reflexao: 'Você tem sido disciplinado nas coisas que importam ou nas coisas urgentes?', declaracao: 'Eu sou disciplinado. O PAPAI me capacita para a consistência que constrói o legado que quero deixar.', treinamento_nome: null, treinamento_texto: null },
  { dia: 53, semana: 8, pilar: 'Viver o Propósito', titulo: 'Quando o propósito custa caro', verso: '"Se alguém quiser vir após mim, negue-se a si mesmo, tome a sua cruz e siga-me." — Mt 16:24', palavra: 'Leão, hoje O PAPAI te chama para a conversa difícil: seguir o propósito vai custar algo. O homem que quer o propósito sem o custo quer o trono sem a cruz.', desafio: 'Escreva: o que seu propósito já custou ou vai custar? Quem pode não aprovar? Por que vale a pena pagar esse preço?', reflexao: 'Você está disposto a pagar o preço real do seu propósito?', declaracao: 'Eu pago o preço. Meu propósito vale cada custo e O PAPAI me capacita para carregar o que Ele me deu.', treinamento_nome: null, treinamento_texto: null },
  { dia: 54, semana: 8, pilar: 'Viver o Propósito', titulo: 'O propósito e a próxima geração', verso: '"As lutas que venci, meus filhos não precisarão vencer."', palavra: 'Leão, hoje O PAPAI te chama para pensar além de você. O propósito que cumpre hoje abre portas que seus filhos vão atravessar sem saber que você pagou o preço.', desafio: 'Escreva uma carta para seus filhos explicando o que está construindo nos 90 dias e por que fez isso por eles.', reflexao: 'Seus filhos vão herdar batalhas que você não venceu ou vitórias que conquistou?', declaracao: 'Eu cumpro meu propósito pela próxima geração. As lutas que venci, meus filhos não precisarão vencer.', treinamento_nome: null, treinamento_texto: null },
  { dia: 55, semana: 8, pilar: 'Viver o Propósito', titulo: 'O propósito no cotidiano', verso: '"O SENHOR guia os passos do homem de bem." — Sl 37:23', palavra: 'Leão, hoje O PAPAI te chama para encontrar o propósito no ordinário. Muitos homens esperam o grande momento e perdem o propósito que está no jantar com os filhos, na conversa com a esposa.', desafio: 'Hoje, perceba em cada interação como pode expressar seu propósito. Ao final do dia, escreva três momentos onde sentiu que estava exatamente onde O PAPAI queria.', reflexao: 'Você tem esperado grandes momentos para viver seu propósito? Quantas oportunidades cotidianas tem deixado passar?', declaracao: 'Meu propósito está no cotidiano. O PAPAI guia cada passo e encontro minha missão nos momentos ordinários.', treinamento_nome: null, treinamento_texto: null },
  { dia: 56, semana: 8, pilar: 'Viver o Propósito', titulo: 'Revisão — o propósito em execução', verso: '"Eu já não vivo, mas Cristo vive em mim." — Gl 2:20', palavra: 'Leão, hoje O PAPAI te chama para uma revisão poderosa: oito semanas completas. Você saiu da identidade sacerdotal e chegou no propósito em execução. Você não é mais o homem do Dia 1.', desafio: 'Escreva: (1) Qual foi a semana mais transformadora? (2) Qual pilar ainda precisa de atenção? (3) O que vai fazer diferente nas últimas quatro semanas?', reflexao: 'Compare quem você era no Dia 1 com quem você é hoje nos relacionamentos, trabalho e espiritualidade.', declaracao: 'Eu não sou mais o mesmo. O PAPAI está cumprindo em mim o que prometeu e as últimas quatro semanas serão as mais importantes.', treinamento_nome: 'Método EVO — Márcio Miqueli', treinamento_texto: 'Leão, oito semanas de formação interna — e agora você está pronto para o próximo nível de execução. O Método EVO do Márcio Miqueli foi um dos treinamentos que mais impactou minha capacidade de sair da visão e entrar na ação. Você tem clareza do propósito. Agora precisa da estrutura para executá-lo.' },

  // ═══════════════════════════════
  // SEMANA 9 — LEGADO EM CONSTRUÇÃO
  // ═══════════════════════════════
  { dia: 57, semana: 9, pilar: 'Legado', titulo: 'Legado começa hoje', verso: '"O homem de bem deixa herança aos filhos dos seus filhos." — Pv 13:22', palavra: 'Leão, hoje O PAPAI te chama para entender que legado não é o que você deixa quando morre — é o que você constrói enquanto vive. Cada conversa com seu filho hoje é legado. Legado não é um evento futuro — é uma prática presente.', desafio: 'Identifique três áreas onde está construindo legado ativamente e três onde está negligenciando. Para cada negligenciada, escreva uma ação concreta.', reflexao: 'Que tipo de legado está construindo — intencional ou acidental?', declaracao: 'Meu legado começa hoje. Cada decisão com integridade é uma pedra na fundação que meus filhos vão herdar.', treinamento_nome: null, treinamento_texto: null },
  { dia: 58, semana: 9, pilar: 'Legado', titulo: 'Multiplicar o que você recebeu', verso: '"Ide, portanto, e fazei discípulos." — Mt 28:19', palavra: 'Leão, hoje O PAPAI te chama para a missão final de todo homem de propósito: multiplicar. Você passou 57 dias sendo formado. Agora é hora de formar.', desafio: 'Identifique uma pessoa em quem vai investir como mentor nos próximos 30 dias. Não um curso — presença, conversa, cobertura. Marque o primeiro encontro.', reflexao: 'Quem está esperando que você invista nele? Quem O PAPAI colocou na sua vida para você multiplicar?', declaracao: 'Eu multiplico. O PAPAI me formou para que eu forme outros e o legado se estenda além de mim.', treinamento_nome: null, treinamento_texto: null },
  { dia: 59, semana: 9, pilar: 'Legado', titulo: 'O leão que chegou ao fim não para', verso: '"Não nos cansemos de fazer o bem, porque a seu tempo ceifaremos." — Gl 6:9', palavra: 'Leão, hoje O PAPAI te chama para uma advertência: completar os 90 dias não é a linha de chegada — é o ponto de partida. A Alcateia não termina no Dia 90. Ela começa.', desafio: 'Escreva os cinco hábitos que vai manter permanentemente após o Dia 90 — um por pilar: sacerdotal, provedor, protetor, presente e propósito.', reflexao: 'Você está tratando esses 90 dias como sprint ou como início de uma maratona?', declaracao: 'Eu não paro no Dia 90. O que O PAPAI construiu em mim é a fundação da vida que vou viver por décadas.', treinamento_nome: null, treinamento_texto: null },
  { dia: 60, semana: 9, pilar: 'Legado', titulo: 'Gratidão pela jornada', verso: '"Em tudo dai graças." — 1 Ts 5:18', palavra: 'Leão, hoje O PAPAI te chama para parar e ser grato. Não pela chegada — pela jornada. Pelos dias difíceis, pelas perguntas que encarou, pelas conversas corajosas.', desafio: 'Escreva uma oração de gratidão específica ao PAPAI por cada uma das semanas — uma frase por semana.', reflexao: 'O que você é grato hoje que não poderia ser no Dia 1? Como sua perspectiva mudou?', declaracao: 'Eu sou grato. O PAPAI me levou por um caminho que transformou quem eu sou.', treinamento_nome: null, treinamento_texto: null },
  { dia: 61, semana: 9, pilar: 'Legado', titulo: 'A carta para o Dia 1', verso: '"Porque eu sei os planos que tenho para vós." — Jr 29:11', palavra: 'Leão, hoje O PAPAI te chama para escrever uma carta para o homem que você era no Dia 1. Não com arrogância — com compaixão e gratidão.', desafio: 'Escreva uma carta de no mínimo uma página para quem você era no Dia 1. O que diria para ele? O que ele precisava ouvir?', reflexao: 'Quem você era no Dia 1 e quem você é hoje — qual é a diferença mais profunda na identidade?', declaracao: 'Eu honro quem eu era porque ele teve coragem de começar. E honro quem me tornei porque O PAPAI foi fiel em cada passo.', treinamento_nome: null, treinamento_texto: null },
  { dia: 62, semana: 9, pilar: 'Legado', titulo: 'A Alcateia cresce', verso: '"Onde dois ou três estiverem reunidos em meu nome, aí estou no meio deles." — Mt 18:20', palavra: 'Leão, hoje O PAPAI te chama para pensar na Alcateia além de você. O leão que chegou ao fim e não convida outros está guardando para si o que foi dado para multiplicar.', desafio: 'Pense em dois ou três homens que precisam desta jornada. Não envie um link — faça uma ligação, tome um café, conte o que aconteceu com você.', reflexao: 'Quem está ao seu redor vivendo no automático que poderia ser transformado por essa jornada?', declaracao: 'Eu convido outros para a Alcateia. O que o PAPAI fez em mim é testemunho e testemunho multiplica.', treinamento_nome: null, treinamento_texto: null },
  { dia: 63, semana: 9, pilar: 'Legado', titulo: 'Revisão — o legado em construção', verso: '"Bem, servo bom e fiel!" — Mt 25:21', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana do legado em construção. Três semanas para o fim — e o que vem agora é a consolidação de tudo.', desafio: 'Escreva: (1) A mudança mais profunda nestes 63 dias. (2) O que vai fazer diferente nas últimas três semanas. (3) Seu compromisso com O PAPAI para os próximos 90 dias após esta jornada.', reflexao: 'Se O PAPAI te dissesse hoje "bem, servo fiel", por qual das mudanças você acredita que Ele diria isso?', declaracao: 'Eu sou fiel no pouco. O PAPAI me confia mais porque cuidei do que Ele colocou nas minhas mãos nestes 63 dias.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 10 — LEGADO: FUNDAÇÃO
  // ═══════════════════════════════
  { dia: 64, semana: 10, pilar: 'Legado', titulo: 'O que é legado real', verso: '"Uma geração louvará as tuas obras à outra geração." — Sl 145:4', palavra: 'Leão, hoje O PAPAI te chama para definir legado com precisão. Legado não é uma fortuna nem um nome em um prédio. É o que as próximas gerações vão falar sobre quem você foi.', desafio: 'Escreva seu testamento não material — não de bens, mas de valores. O que quer transmitir para seus filhos sobre fé, trabalho, relacionamento e integridade?', reflexao: 'Se seus filhos fossem descrever seu legado daqui a 30 anos, o que eles diriam?', declaracao: 'Meu legado é o que transmito, não o que acumulo. O PAPAI me chamou para deixar algo que dure além da minha vida.', treinamento_nome: null, treinamento_texto: null },
  { dia: 65, semana: 10, pilar: 'Legado', titulo: 'Legado espiritual', verso: '"Instruí o jovem no caminho em que deve andar." — Pv 22:6', palavra: 'Leão, hoje O PAPAI te chama para o legado mais valioso: a fé transmitida. Fé transmitida não é levar filho à igreja — é viver a fé em casa, nas decisões, nas crises.', desafio: 'Avalie o legado espiritual que está transmitindo: seus filhos veem você orar? Pedir perdão? Confiar no PAPAI nas crises?', reflexao: 'O que seus filhos estão aprendendo sobre O PAPAI só de observar como você vive?', declaracao: 'Eu transmito fé. Meu legado espiritual é mais valioso que qualquer herança material.', treinamento_nome: null, treinamento_texto: null },
  { dia: 66, semana: 10, pilar: 'Legado', titulo: 'Legado familiar', verso: '"Honra teu pai e tua mãe... para que te vá bem." — Ef 6:2-3', palavra: 'Leão, hoje O PAPAI te chama para pensar no legado familiar como estrutura. Família de legado não acontece por acidente. Tradições que formam identidade. O leão que não constrói cultura familiar intencional deixa seus filhos sem raiz.', desafio: 'Crie ou fortaleça uma tradição familiar — um ritual semanal, uma história que vai contar regularmente. Algo que seus netos vão conhecer.', reflexao: 'Qual tradição você recebeu e quer transmitir? Qual quer criar do zero?', declaracao: 'Eu construo cultura familiar. As tradições que crio hoje formam quem meus filhos serão amanhã.', treinamento_nome: null, treinamento_texto: null },
  { dia: 67, semana: 10, pilar: 'Legado', titulo: 'Legado profissional', verso: '"O nome do SENHOR é uma torre forte; o justo corre para ela." — Pv 18:10', palavra: 'Leão, hoje O PAPAI te chama para pensar no legado no trabalho. Não o tamanho da empresa — a integridade com que a construiu. Os funcionários que formou. Legado profissional é reputação construída ao longo de décadas.', desafio: 'Pense em alguém da sua equipe que pode investir intencionalmente — não como ferramenta, mas como pessoa. Faça isso esta semana.', reflexao: 'Como as pessoas que trabalham com você descrevem sua liderança?', declaracao: 'Meu legado profissional é integridade e pessoas formadas. O PAPAI me chamou para ser formador.', treinamento_nome: null, treinamento_texto: null },
  { dia: 68, semana: 10, pilar: 'Legado', titulo: 'Legado comunitário', verso: '"Buscai o bem da cidade para a qual vos fiz transportar." — Jr 29:7', palavra: 'Leão, hoje O PAPAI te chama para pensar além da família: qual é o seu legado na comunidade? O leão de legado não consome a comunidade — a serve.', desafio: 'Identifique uma forma de servir sua comunidade com tempo, habilidade ou influência. Dê um primeiro passo.', reflexao: 'O lugar onde você vive está melhor por você estar ali?', declaracao: 'Eu sirvo minha comunidade. O PAPAI me colocou onde estou para deixar esse lugar melhor do que encontrei.', treinamento_nome: null, treinamento_texto: null },
  { dia: 69, semana: 10, pilar: 'Legado', titulo: 'Legado e reconciliação', verso: '"Vai primeiro reconciliar-te com teu irmão." — Mt 5:23-24', palavra: 'Leão, hoje O PAPAI te chama para o lado mais difícil do legado: reconciliação. O perdão que você oferece não é para o outro — é para você e para o legado que quer deixar.', desafio: 'Identifique uma relação rompida onde há amargura. Leve ao altar do PAPAI e declare o perdão em oração.', reflexao: 'Existe alguém com quem você precisa se reconciliar antes do Dia 90?', declaracao: 'Eu perdoo. Meu legado não carrega amargura. O PAPAI me liberta das dívidas emocionais.', treinamento_nome: null, treinamento_texto: null },
  { dia: 70, semana: 10, pilar: 'Legado', titulo: 'Revisão — o legado ganha forma', verso: '"Toda a terra que você está vendo darei a você e à sua descendência para sempre." — Gn 13:15', palavra: 'Leão, hoje O PAPAI te chama para revisar a semana do legado. Dez semanas completas. Você está a duas semanas do fim.', desafio: 'Escreva: (1) Qual dimensão do legado está mais sólida? (2) Qual ainda precisa de trabalho? (3) O que vai fazer nas últimas duas semanas para consolidar tudo?', reflexao: 'Se você morresse amanhã, qual seria o legado que deixaria? É suficiente?', declaracao: 'Meu legado está sendo construído hoje. O PAPAI me dá terra para cada passo que dou em obediência.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 11 — LEGADO: CONSOLIDAÇÃO
  // ═══════════════════════════════
  { dia: 71, semana: 11, pilar: 'Legado', titulo: 'Consolidar os rituais', verso: '"Quem é fiel no mínimo, também é fiel no muito." — Lc 16:10', palavra: 'Leão, hoje O PAPAI te chama para revisar os rituais que construiu. Os hábitos instalados nestes 71 dias precisam ser consolidados — não como obrigação, mas como identidade.', desafio: 'Faça uma auditoria dos seus rituais: quais se tornaram hábitos reais e quais ainda são esforço? Para os que ainda são esforço, ajuste horário ou formato.', reflexao: 'Quais hábitos desta jornada você não consegue mais imaginar abandonar?', declaracao: 'Meus rituais são minha identidade. O que O PAPAI construiu em mim não é programa — é quem eu sou.', treinamento_nome: null, treinamento_texto: null },
  { dia: 72, semana: 11, pilar: 'Legado', titulo: 'O leão volta ao básico', verso: '"Lembra-te, pois, de onde caíste, arrepende-te e pratica as primeiras obras." — Ap 2:5', palavra: 'Leão, hoje O PAPAI te chama para verificar: o básico ainda está sólido? É fácil nos últimos dias ficar animado com conquistas e negligenciar o que sustenta tudo.', desafio: 'Volte à Semana 1 e releia a missão do Dia 1. Compare quem você era com quem você é. Escolha um pilar que enfraqueceu e reforce com uma ação concreta.', reflexao: 'Qual é o pilar que você tem negligenciado à medida que avançou?', declaracao: 'Eu cuido do básico. O PAPAI me ensinou que grandeza é consistência no simples.', treinamento_nome: null, treinamento_texto: null },
  { dia: 73, semana: 11, pilar: 'Legado', titulo: 'Falar sobre a jornada', verso: '"Que o resgatado do SENHOR o diga." — Sl 107:2', palavra: 'Leão, hoje O PAPAI te chama para usar sua voz. Seu testemunho não é para você — é para o homem que ainda está no automático.', desafio: 'Hoje, conte para alguém o que aconteceu com você nestes 73 dias. Não o programa. A transformação. Seja específico.', reflexao: 'Você tem compartilhado sua jornada ou guardado para si? O que te impede de falar sobre o que O PAPAI fez?', declaracao: 'Eu falo sobre o que O PAPAI fez. Meu testemunho é semente que multiplica na vida de outros homens.', treinamento_nome: null, treinamento_texto: null },
  { dia: 74, semana: 11, pilar: 'Legado', titulo: 'O leão e a comunidade da Alcateia', verso: '"Não forsaqueis a vossa congregação." — Hb 10:25', palavra: 'Leão, hoje O PAPAI te chama para o valor da comunidade intencional. O leão que abandona a alcateia após 90 dias perde o ambiente que sustenta a transformação.', desafio: 'Identifique como vai manter conexão com a Alcateia após o Dia 90. Defina a estrutura e convide pelo menos um homem para fazer parte.', reflexao: 'Você tem relações masculinas que cobrem, afiam e impulsionam?', declaracao: 'Eu faço parte da Alcateia. A comunidade que O PAPAI me deu é proteção e aceleração do meu propósito.', treinamento_nome: null, treinamento_texto: null },
  { dia: 75, semana: 11, pilar: 'Legado', titulo: 'Carta para seus filhos', verso: '"Estas coisas escrevo a vós outros para que a vossa alegria seja completa." — 1 Jo 1:4', palavra: 'Leão, hoje O PAPAI te chama para um dos atos mais poderosos de legado: escrever para seus filhos. Você vai escrever para que saibam quem o pai era de verdade.', desafio: 'Escreva uma carta para cada filho — específica para cada um. O que você vê neles, o que crê para eles, o que quer que saibam sobre O PAPAI e sobre você.', reflexao: 'Seus filhos sabem o que você pensa sobre eles? Eles conhecem os sonhos que tem para eles?', declaracao: 'Eu escrevo para meus filhos. Minhas palavras para eles são legado que permanece quando eu não estiver mais aqui.', treinamento_nome: null, treinamento_texto: null },
  { dia: 76, semana: 11, pilar: 'Legado', titulo: 'O leão que descansa', verso: '"Vinde a mim, todos os que estais cansados, e eu vos darei descanso." — Mt 11:28', palavra: 'Leão, hoje O PAPAI te chama para algo raro nos homens de desempenho: descansar sem culpa. O leão que não descansa está dizendo que tudo depende dele. O leão que descansa diz que O PAPAI sustenta o que construiu.', desafio: 'Planeje seu dia de Shabbat desta semana: sem trabalho, sem obrigações. Só descanso, presença com a família e renovação.', reflexao: 'Você tem descansado ou apenas parado quando não aguenta mais?', declaracao: 'Eu descanso com confiança. O PAPAI sustenta o que construí enquanto eu recarrego para continuar.', treinamento_nome: null, treinamento_texto: null },
  { dia: 77, semana: 11, pilar: 'Legado', titulo: 'Revisão — a consolidação', verso: '"Perseverai na oração, velando nela com ação de graças." — Cl 4:2', palavra: 'Leão, hoje O PAPAI te chama para a penúltima revisão. Onze semanas. Setenta e sete dias. A última semana começa amanhã.', desafio: 'Escreva: (1) O que está mais sólido em você hoje? (2) Qual compromisso quer renovar com O PAPAI antes do Dia 90? (3) Como vai celebrar o Dia 90 com sua família?', reflexao: 'Você chegou até aqui. O que isso diz sobre quem você é?', declaracao: 'Eu perseverei. O PAPAI me sustentou em cada dia difícil e chego na última semana mais forte do que no primeiro dia.', treinamento_nome: null, treinamento_texto: null },

  // ═══════════════════════════════
  // SEMANA 12 — LEGADO: A CHEGADA
  // ═══════════════════════════════
  { dia: 78, semana: 12, pilar: 'Legado', titulo: 'A semana final começa', verso: '"Olhando para Jesus, autor e consumador da nossa fé." — Hb 12:2', palavra: 'Leão, hoje O PAPAI te chama para entrar na última semana com os olhos fixos no que importa. O Dia 90 não é o fim. É o primeiro dia do resto da sua vida como leão de propósito.', desafio: 'Hoje, releia os textos que escreveu ao longo dos 90 dias. Identifique a transformação mais profunda e escreva uma oração de gratidão específica ao PAPAI.', reflexao: 'Você entrou nesta jornada esperando o quê? O que O PAPAI entregou que não esperava?', declaracao: 'Eu chego na última semana com gratidão e determinação. O PAPAI me formou e agora me lança.', treinamento_nome: null, treinamento_texto: null },
  { dia: 79, semana: 12, pilar: 'Legado', titulo: 'Integrar os nove pilares', verso: '"Que o Deus da paz vos santifique em tudo." — 1 Ts 5:23', palavra: 'Leão, hoje O PAPAI te chama para integrar o que aprendeu. Sacerdote, Provedor, Protetor, Presente, Próspero, Honrar a Esposa, Propósito, Legado — não são caixas separadas. São dimensões de um homem inteiro.', desafio: 'Desenhe os nove pilares como círculos interligados. Escreva em cada um onde você está agora. Identifique qual pilar fortalece todos os outros.', reflexao: 'Como os nove pilares se conectam na sua vida prática?', declaracao: 'Eu sou um homem inteiro. O PAPAI me formou em todas as dimensões e cada pilar fortalece os outros.', treinamento_nome: null, treinamento_texto: null },
  { dia: 80, semana: 12, pilar: 'Legado', titulo: 'O leão deixa marcas', verso: '"A memória do justo é abençoada." — Pv 10:7', palavra: 'Leão, hoje O PAPAI te chama para pensar nas marcas que você deixa. A marca no caráter do filho quando se senta com ele sem celular. A marca no coração da esposa quando pede perdão.', desafio: 'Hoje, intencione deixar uma marca em cada pessoa da sua família — algo específico e memorável. Hoje.', reflexao: 'Que marcas você está deixando nas pessoas mais próximas? Constroem ou diminuem?', declaracao: 'Eu deixo marcas boas. A memória que as pessoas têm de mim é construída hoje, em cada escolha de como trato quem amo.', treinamento_nome: null, treinamento_texto: null },
  { dia: 81, semana: 12, pilar: 'Legado', titulo: 'Preparar os próximos 90 dias', verso: '"Os planos do diligente tendem para a abundância." — Pv 21:5', palavra: 'Leão, hoje O PAPAI te chama para planejar. Completar os 90 dias sem planejar os próximos 90 é como correr uma maratona e não saber o que comer depois.', desafio: 'Escreva um plano para os próximos 90 dias: três metas por pilar, três relacionamentos para aprofundar, três hábitos para consolidar.', reflexao: 'O que você sabe hoje que vai mudar como planeja os próximos 90 dias?', declaracao: 'Eu planejo com sabedoria. O PAPAI me deu clareza e vou usá-la para construir os próximos 90 dias.', treinamento_nome: null, treinamento_texto: null },
  { dia: 82, semana: 12, pilar: 'Legado', titulo: 'Celebrar com a família', verso: '"Entrai no gozo do vosso Senhor." — Mt 25:23', palavra: 'Leão, hoje O PAPAI te chama para celebrar com quem foi impactado pela sua transformação. Sua família viveu esta jornada com você. A celebração do Dia 90 é gratidão compartilhada.', desafio: 'Planeje a celebração do Dia 90 com sua família — um jantar, uma noite diferente. Intencional. Compartilhe com eles o que esses 90 dias significaram.', reflexao: 'Como sua família foi impactada pela sua jornada? O que perceberam de diferente em você?', declaracao: 'Eu celebro com quem amo. A vitória do PAPAI em mim é também deles.', treinamento_nome: null, treinamento_texto: null },
  { dia: 83, semana: 12, pilar: 'Legado', titulo: 'O compromisso eterno', verso: '"Quanto a mim e à minha família, serviremos ao SENHOR." — Js 24:15', palavra: 'Leão, hoje O PAPAI te chama para renovar o compromisso mais fundamental — não com um programa, mas com Ele. O compromisso de Josué não era temporário. Era uma declaração de identidade familiar para sempre.', desafio: 'Renove seu compromisso com O PAPAI em oração específica por cada pilar. Uma declaração por pilar. Em voz alta.', reflexao: 'Seu compromisso com O PAPAI é mais sólido hoje do que no Dia 1? O que mudou no seu coração?', declaracao: 'Eu e minha família serviremos ao SENHOR. Este não é um compromisso de 90 dias — é a declaração da minha vida.', treinamento_nome: null, treinamento_texto: null },
  { dia: 84, semana: 12, pilar: 'Legado', titulo: 'Véspera do Dia 90', verso: '"O SENHOR completará o que concerne a mim." — Sl 138:8', palavra: 'Leão, hoje O PAPAI te chama para um momento de silêncio e gratidão. Amanhã é o Dia 90. Você chegou. Não porque foi perfeito — porque perseverou.', desafio: 'Hoje, passe tempo em silêncio diante do PAPAI. Não peça nada. Apenas ouça. Escreva o que ouviu.', reflexao: 'O que O PAPAI completou em você nestes 90 dias que não conseguia imaginar no Dia 1?', declaracao: 'O PAPAI está completando em mim o que começou. Chego ao Dia 90 não como chegada, mas como lançamento.', treinamento_nome: null, treinamento_texto: null },
  { dia: 85, semana: 12, pilar: 'Legado', titulo: 'O leão que não desiste', verso: '"Combati o bom combate, acabei a carreira, guardei a fé." — 2 Tm 4:7', palavra: 'Leão, hoje O PAPAI te chama para reconhecer o que você fez: você não desistiu. Combater o bom combate não significa vencer tudo — significa não abandonar o campo. Você está no Dia 85. Cinco dias para o fim.', desafio: 'Escreva os três momentos desta jornada em que mais quis desistir. Para cada um, escreva o que te fez continuar. Essa lista é seu arsenal para os próximos desafios.', reflexao: 'O que essa jornada revelou sobre sua capacidade de perseverar?', declaracao: 'Eu não desisto. O PAPAI me deu força para chegar até aqui e essa mesma força me leva além do Dia 90.', treinamento_nome: null, treinamento_texto: null },
  { dia: 86, semana: 12, pilar: 'Legado', titulo: 'O leão que cuida de si mesmo', verso: '"Ou não sabeis que o vosso corpo é o templo do Espírito Santo?" — 1 Co 6:19', palavra: 'Leão, hoje O PAPAI te chama para uma dimensão que os homens de propósito frequentemente negligenciam: o cuidado do próprio corpo. Sono, exercício, alimentação, saúde preventiva — são administração do templo que O PAPAI te deu.', desafio: 'Avalie sua saúde física: você dorme o suficiente? Se exercita? Há algo que adiou no médico? Identifique uma ação de cuidado com o seu corpo e tome essa ação esta semana.', reflexao: 'Você tem tratado seu corpo como templo ou como ferramenta descartável?', declaracao: 'Eu cuido do templo que O PAPAI me deu. Meu corpo saudável é um ato de mordomia e de amor pela minha família.', treinamento_nome: null, treinamento_texto: null },
  { dia: 87, semana: 12, pilar: 'Legado', titulo: 'O leão e o dinheiro do Reino', verso: '"Honra ao SENHOR com os teus bens e com as primícias de todos os teus frutos." — Pv 3:9', palavra: 'Leão, hoje O PAPAI te chama para um último olhar sobre finanças — não como preocupação, mas como mordomia. O homem que honra ao SENHOR com os seus bens reconhece que tudo veio do PAPAI e será administrado na direção do PAPAI.', desafio: 'Revise sua prática de generosidade: você tem honrado ao PAPAI com as primícias? Você tem um plano estruturado de dízimo e oferta? Se não tem, defina hoje.', reflexao: 'Sua relação com o dinheiro reflete alguém que acredita que tudo pertence ao PAPAI?', declaracao: 'Eu honro ao PAPAI com o que tenho. Meu dinheiro é ferramenta do Reino e administro com gratidão e generosidade.', treinamento_nome: null, treinamento_texto: null },
  { dia: 88, semana: 12, pilar: 'Legado', titulo: 'O leão que ouve a voz do PAPAI', verso: '"As minhas ovelhas ouvem a minha voz." — Jo 10:27', palavra: 'Leão, hoje O PAPAI te chama para uma das habilidades mais importantes: ouvir a voz do PAPAI com clareza. Não apenas em momentos de crise — no cotidiano. O leão que desenvolveu intimidade nestes 88 dias tem ouvidos mais treinados.', desafio: 'Passe 20 minutos em silêncio absoluto. Faça uma pergunta específica ao PAPAI sobre algo da sua vida. Escreva o que vier.', reflexao: 'Você consegue distinguir a voz do PAPAI da sua própria voz? Como essa habilidade cresceu nestes 88 dias?', declaracao: 'Eu ouço a voz do PAPAI. A intimidade que construí nestes dias afiou meus ouvidos para o que Ele fala no cotidiano.', treinamento_nome: null, treinamento_texto: null },
  { dia: 89, semana: 12, pilar: 'Legado', titulo: 'A última noite — vigília de gratidão', verso: '"Esta é a noite do SENHOR, vigília que todos os filhos de Israel devem guardar." — Ex 12:42', palavra: 'Leão, hoje O PAPAI te chama para uma vigília — não de ansiedade, mas de gratidão. Você chegou a essa noite. Amanhã é o seu Dia 90. Esta noite é para guardar, agradecer e se preparar para celebrar.', desafio: 'Esta noite, antes de dormir, releia as declarações que escreveu ao longo dos 90 dias — pelo menos uma por semana. Deixe a progressão te mostrar quem você era e quem se tornou.', reflexao: 'O que vai levar desta jornada para o resto da vida? Não os hábitos — a identidade. Quem você é agora que não era no Dia 1?', declaracao: 'Eu chego à última noite com paz. O PAPAI foi fiel em cada dia desta jornada e amanhã celebro o que Ele fez em mim.', treinamento_nome: null, treinamento_texto: null },
  { dia: 90, semana: 12, pilar: 'Legado', titulo: 'DIA 90 — O leão que você é', verso: '"Tudo posso naquele que me fortalece." — Fp 4:13', palavra: 'Leão, hoje O PAPAI te chama para celebrar. Não o programa. Você. Noventa dias atrás você era um homem que decidiu parar de viver no automático. Hoje você é sacerdote, provedor, protetor, presente, próspero, um marido que honra, um homem de propósito e um construtor de legado. Isso não é teoria. É quem você é.', desafio: 'Reúna sua família. Leia a carta que escreveu para seus filhos. Compartilhe o que esses 90 dias significaram. E amanhã, no Dia 91, acorde e faça a mesma coisa que fez no Dia 1: entre no teu quarto secreto antes de tudo.', reflexao: 'Quem você era no Dia 1 e quem você é no Dia 90? Essa diferença é o que O PAPAI fez em você. Escreva. Guarde. Releia quando a vida tentar te convencer de que você não mudou.', declaracao: 'Eu sou leão. Fui chamado pelo PAPAI, formado em 90 dias, lançado para uma vida de propósito. O milagre começa quando as desculpas terminam — e as minhas terminaram há 90 dias.', treinamento_nome: null, treinamento_texto: null }
];

async function seed() {
  console.log(`Iniciando seed de ${MISSOES.length} missões...`);

  // Inserir em lotes de 10 para evitar timeout
  const LOTE = 10;
  let inseridos = 0;

  for (let i = 0; i < MISSOES.length; i += LOTE) {
    const lote = MISSOES.slice(i, i + LOTE);
    const { data, error } = await supabase
      .from('alcateia_missoes')
      .upsert(lote, { onConflict: 'dia' });

    if (error) {
      console.error(`Erro no lote ${i / LOTE + 1}:`, error.message);
      process.exit(1);
    }

    inseridos += lote.length;
    console.log(`✓ ${inseridos}/${MISSOES.length} missões inseridas`);
  }

  console.log('\n✅ Seed completo! Todos os 90 dias estão no Supabase.');

  // Verificação final
  const { count } = await supabase
    .from('alcateia_missoes')
    .select('*', { count: 'exact', head: true });

  console.log(`📊 Total na tabela: ${count} missões`);
}

seed().catch(console.error);
